### ISSUE TITLE
"IREE system clock needs to be set up for your platform"

### ISSUE THREAD

**Issue by GeoBouz** [iml130/iree-bare-metal-arm#313] opened 2024-01-09 16:20 UTC
Hello! When I try to cmake --build . --target sample_vmvx_sync I get an error about "IREE system clock needs to be set up for your platform". In more details:
realpath/iree-bare-metal-arm/third_party/iree/runtime/src/iree/base/time.c: In function ‘iree_time_now’:
realpath/iree-bare-metal-arm/third_party/iree/runtime/src/iree/base/time.c:39:2: error: #error "IREE system clock needs to be set up for your platform"
   39 | #error "IREE system clock needs to be set up for your platform"
      |  ^~~~~
realpath/iree-bare-metal-arm/iree-bare-metal-arm/third_party/iree/runtime/src/iree/base/time.c:41:1: error: control reaches end of non-void function [-Werror=return-type]
   41 | }

**Comment by marbre** [comment] 2024-01-11 10:06
Thanks for the additional information. I still can't reproduce the error and building the `sample_vmvx_sync` works for me. I still assume that some paths might be incorrect, at least the one to the toolchain file. Can you extract the `CMAKE_TOOLCHAIN_FILE` variable with `grep CMAKE_TOOLCHAIN_FILE CMakeCache.txt` (executed in the build folder) and check if it points to the correct location / file?

**Comment by GeoBouz** [comment] 2024-01-11 17:55
Inside the build folder I get CMakeCache.txt: No such file or directory. But in the parent folder of build that I run the cmake --build . --target sample_vmvx_sync comants I get CMAKE_TOOLCHAIN_FILE:UNINITIALIZED=realpath/iree-bare-metal-arm/iree-bare-metal-arm/build_tools/cmake/arm-none-eabi-gcc.cmake that is the same path as used. Should it be available also in the build folder?

**Comment by marbre** [comment] 2024-01-12 09:48
To clarify, the folder where the `CMakeCache.txt` is located **is / should be** the build folder! Seems like this is the problem your facing and if you execute the `cmake --build` command in a different location it cannot find the toolchain file, resulting in the missing function implementation.

**Comment by marbre** [comment] 2024-01-18 16:08
Closing this issue for now. @GeoBouz please re-open if the issue persists and although feel free to open further issues; in particular if you think that we can improve our documentation!

**Closed by marbre** 2024-01-18 16:08 UTC
