### ISSUE TITLE
host build failure with ninja

### ISSUE THREAD

**Issue by powderluv** [iml130/iree-bare-metal-arm#7] opened 2021-08-28 18:30 UTC
When trying to build host tools with ninja: 

CMake Error at build_tools/third_party/flatcc/CMakeLists.txt:54 (add_executable):
  The install of the iree-flatcc-cli target requires changing an RPATH from
  the build tree, but this is not supported with the Ninja generator unless
  on an ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may
  be set to avoid this relinking step.

**Comment by marbre** [comment] 2021-08-29 08:08
Thanks for reporting. Unfortunately, I cannot reproduce this on a machine with Ubuntu 20.04 LTS. Trying to reproduce, I used a fresh clone and copy-pasted the https://github.com/iml130/iree-bare-metal-arm#host-build instructions. With these instructions, the error your reported didn't show up. Can you provide further details?

**Comment by marbre** [comment] 2021-09-08 07:38
As I cannot investigate without further information, I am closing this for now. Feel free to reopen if the issue still persists.

**Closed by marbre** 2021-09-08 07:38 UTC
